package grafioschtrader.nls;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeSet;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import grafiosch.nls.NlsBundleInspector;
import grafiosch.nls.NlsBundleInspector.Bundle;
import grafiosch.nls.NlsKeyMapper;

/**
 * Emits the inventory of keys each module actually serves, which is the machine-readable answer to "who owns this
 * text and what does the client call it".
 *
 * <p>
 * The inventory is produced here, in Java, rather than by the migration script, so that {@link NlsKeyMapper} stays the
 * only implementation of the mapping rules. The script consumes {@code target/nls-inventory-*.tsv} and therefore never
 * needs to reproduce the transform in another language, where it could drift.
 * </p>
 */
class NlsInventoryTest {

  /** Where the generated inventories land; {@code target} is deliberately not checked in. */
  static final Path INVENTORY_DIRECTORY = Path.of("target");

  @Test
  @DisplayName("Write the per-module key inventory for the migration tooling")
  void writeInventories() {
    int baseKeys = writeInventory("base", NlsBundleInspector.BASE_BUNDLE);
    int commonKeys = writeInventory("common", NlsBundleInspector.COMMON_BUNDLE);
    assertThat(baseKeys).as("grafiosch-base must serve texts").isPositive();
    assertThat(commonKeys).as("grafioschtrader-common must serve texts").isPositive();
  }

  /**
   * Writes one module's inventory as {@code rawKey <TAB> clientKey}, sorted by raw key.
   *
   * @param moduleAlias short module name used in the file name
   * @param bundle      class path base name of the module's bundle pair
   * @return the number of keys written
   */
  private static int writeInventory(String moduleAlias, String bundle) {
    Bundle english = NlsBundleInspector.load(bundle, null);
    List<String> lines = new ArrayList<>();
    lines.add("# Generated by NlsInventoryTest -- do not edit, do not check in.");
    lines.add("# rawKey\tclientKey");
    for (String rawKey : new TreeSet<>(english.keys())) {
      lines.add(rawKey + "\t" + NlsKeyMapper.mapToString(rawKey));
    }
    Path target = INVENTORY_DIRECTORY.resolve("nls-inventory-" + moduleAlias + ".tsv");
    try {
      Files.createDirectories(target.getParent());
      Files.write(target, lines, StandardCharsets.UTF_8);
    } catch (IOException e) {
      throw new UncheckedIOException("Cannot write " + target, e);
    }
    return english.keys().size();
  }
}
