-- select CONCAT("ALTER TABLE ", col.table_name, " CHANGE ", col.column_name, " ", col.column_name, " DOUBLE(", col.numeric_precision, ",", col.numeric_scale, ") ", IF(col.is_nullable = "YES", "NULL DEFAULT NULL", "NOT NULL"), ";") from information_schema.columns col join information_schema.tables tab on tab.table_schema = col.table_schema and tab.table_name = col.table_name and tab.table_type = 'BASE TABLE' where col.data_type in ('double') and col.table_schema not in ('information_schema', 'sys', 'performance_schema', 'mysql') and col.table_schema = 'grafioschtrader' and col.numeric_precision = 16 order by col.table_schema, col.table_name, col.ordinal_position; 

ALTER TABLE dividend CHANGE amount amount DOUBLE(22,8) NOT NULL;
ALTER TABLE dividend CHANGE amount_adjusted amount_adjusted DOUBLE(22,10) NOT NULL;
ALTER TABLE gt_net_lastprice CHANGE open open DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE gt_net_lastprice CHANGE low low DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE gt_net_lastprice CHANGE high high DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE gt_net_lastprice CHANGE last last DOUBLE(22,8) NOT NULL;
ALTER TABLE gt_net_lastprice_detail_log CHANGE last last DOUBLE(22,8) NOT NULL;
ALTER TABLE historyquote CHANGE close close DOUBLE(22,8) NOT NULL;
ALTER TABLE historyquote CHANGE open open DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE historyquote CHANGE high high DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE historyquote CHANGE low low DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE imp_trans_pos CHANGE currency_ex_rate currency_ex_rate DOUBLE(22,10) NULL DEFAULT NULL;
ALTER TABLE imp_trans_pos CHANGE quotation quotation DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE imp_trans_pos CHANGE tax_cost tax_cost DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE imp_trans_pos CHANGE transaction_cost transaction_cost DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE imp_trans_pos CHANGE cashaccount_amount cashaccount_amount DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE imp_trans_pos CHANGE accrued_interest accrued_interest DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE net_lastprice_detail_log CHANGE last last DOUBLE(22,8) NOT NULL;
ALTER TABLE securitycurrency CHANGE s_prev_close s_prev_close DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE securitycurrency CHANGE s_change_percentage s_change_percentage DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE securitycurrency CHANGE s_last s_last DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE securitycurrency CHANGE s_low s_low DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE securitycurrency CHANGE s_high s_high DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE transaction CHANGE quotation quotation DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE transaction CHANGE tax_cost tax_cost DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE transaction CHANGE transaction_cost transaction_cost DOUBLE(22,8) NULL DEFAULT NULL;
ALTER TABLE transaction CHANGE currency_ex_rate currency_ex_rate DOUBLE(20,10) NULL DEFAULT NULL;
ALTER TABLE transaction CHANGE cashaccount_amount cashaccount_amount DOUBLE(22,8) NOT NULL COMMENT 'Amount which is added to the cash account';
ALTER TABLE transaction CHANGE asset_investment_value_1 asset_investment_value_1 DOUBLE(22,8) NULL DEFAULT NULL COMMENT 'Used for accrued interest with Bonds and daily holding costs with CFD';
ALTER TABLE transaction CHANGE asset_investment_value_2 asset_investment_value_2 DOUBLE(22,8) NULL DEFAULT NULL COMMENT 'CFD holds the value per point';