export enum TradingPlatformFeePlan {
  FP_FREE = 0,
  FP_FLAT = 1,
  FP_PER_SHARE = 2,
  FP_PER_AMOUNT_PERCENTAGE = 3,
  FP_PER_AMOUNT_GRADUATED = 4,
  FP_FLAT_OR_PER_AMOUNT_PERCENTAGE = 5,
  FP_FLAT_OR_PER_AMOUNT_GRADUATED = 6,
  FP_MIXED = 7
}
