package grafiosch.entities;

import java.time.LocalDate;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import grafiosch.BaseConstants;
import grafiosch.common.PropertyAlwaysUpdatable;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;

@Schema(description = """
    This GTNet configuration contains the general configuration and is not transferred externally.
    Once a successful handshake has been made with a GT instance, such an entity is created.""")
@Entity
@Table(name = GTNetConfig.TABNAME)
public class GTNetConfig extends BaseID<Integer> {

  public static final String TABNAME = "gt_net_config";

  @Id
  @Schema(description = "Primary key, shared with GTNet. References the parent GTNet domain entry.")
  @Column(name = "id_gt_net")
  private Integer idGtNet;

  @JsonIgnore
  @Schema(description = """
      Authentication token generated by this server during the first handshake. This token is sent to the remote
      domain and stored there as tokenRemote. The remote domain must include this token in the Authorization header
      when making requests to this server. Marked @JsonIgnore to prevent accidental exposure via REST API.""")
  @Column(name = "token_this")
  private String tokenThis;

  @JsonIgnore
  @Schema(description = """
      Authentication token received from the remote domain during the first handshake. This token must be included
      in the Authorization header when this server makes requests to the remote domain. Marked @JsonIgnore to
      prevent accidental exposure via REST API. Set to null if the handshake has not been completed.""")
  @Column(name = "token_remote")
  private String tokenRemote;

  @Schema(description = """
      Count of requests received from the remote domain on the day named by dailyRequestLimitDate. Raised for every
      incoming request that is charged to the budget and compared against the dailyRequestLimit of the local GTNet
      entry; once it reaches that limit the remote is answered with GT_NET_DAILY_REQUEST_LIMIT_EXCEEDED_S. There is
      no reset job: the first charged request of a new UTC day rolls both counters over together with
      dailyRequestLimitDate.""")
  @Column(name = "daily_req_limit_count")
  private Integer dailyRequestLimitCount;

  @Schema(description = """
      Count of requests this server has made to the remote domain on the day named by dailyRequestLimitDate. Used to
      self-limit outgoing requests before running into the remote's refusal, by comparing it against the
      dailyRequestLimit the remote published to us. Rolls over with the incoming counter on the first charged
      request of a new UTC day.""")
  @Column(name = "daily_req_limit_remote_count")
  private Integer dailyRequestLimitRemoteCount;

  @Schema(description = """
      UTC day the two daily request counters belong to. Maintained by the counting statements themselves: when a
      request is charged and this date is not today, both counters start again from zero. Null as long as no request
      has ever been charged for this remote.""")
  @JsonFormat(pattern = BaseConstants.STANDARD_DATE_FORMAT)
  @Column(name = "daily_req_limit_date")
  private LocalDate dailyRequestLimitDate;

  @Schema(description = """
      Timestamp of the last update when supplier details were fetched from this remote domain.
      Updated through periodic polling or manual triggering.""")
  @JsonFormat(pattern = BaseConstants.STANDARD_DATE_TIME_FORMAT)
  @Column(name = "supplier_last_update")
  private LocalDateTime supplierLastUpdate;

  @Schema(description = """
      Indicates whether this remote domain has been granted access to receive our server list. Set to true when we
      respond with GT_NET_UPDATE_SERVERLIST_ACCEPT_S (manually or automatically). Set to false when we receive
      GT_NET_UPDATE_SERVERLIST_REVOKE_SEL_C from them or when we explicitly revoke their access.""")
  @Column(name = "serverlist_access_granted")
  private boolean serverlistAccessGranted;

  @Schema(description = """
      Counter that tracks the number of request violations from this remote domain. Incremented when the remote
      sends a request that exceeds the configured max_limit for an entity kind (e.g., requesting more than 300
      instruments in a single lastprice request). Used to identify misbehaving clients. Max value is 99. Once it
      reaches g.max.limit.request.exceeded.count the remote's exchange requests are refused, so an administrator
      resets the counter here to admit the peer again.""")
  @PropertyAlwaysUpdatable
  @Min(value = 0)
  @Max(value = 99)
  @Column(name = "request_violation_count")
  private Byte requestViolationCount = 0;

  @Schema(description = """
      TCP connection timeout in seconds for this peer (5-40). When null, the global default from
      GlobalParameters (g.gnet.connection.timeout, default 30s) is used. Allows per-peer tuning
      for peers with different network latencies.""")
  @PropertyAlwaysUpdatable
  @Min(value = 5)
  @Max(value = 40)
  @Column(name = "connection_timeout")
  private Byte connectionTimeout;

  @Schema(description = """
      UTC timestamp when the first successful handshake was completed with this remote domain.
      Used by the GTNetFutureMessageDeliveryTask to determine which remotes should receive pending
      future-oriented messages that were created before the handshake completed.""")
  @Column(name = "handshake_timestamp")
  private LocalDateTime handshakeTimestamp;

  @Schema(description = """
      UTC instant of the last first contact this peer sent that was refused because a handshake with it already
      exists. A peer whose own credentials are gone - a rebuilt database, a restored backup, a moved instance -
      cannot repair the connection by itself and cannot even ask, because an administrative message requires the
      very handshake it is being refused. This stamp is what tells the administrator on this side that someone
      wants back in, and the GTNet setup table turns it into a visible marker on the peer's row. It is cleared
      once the peer has handshaked again or the administrator has allowed a new handshake.""")
  @JsonFormat(pattern = BaseConstants.STANDARD_LOCAL_DATE_TIME)
  @Column(name = "reconnect_requested_time")
  private LocalDateTime reconnectRequestedTime;

  @JsonIgnore
  @Schema(description = """
      The token that tokenThis replaced at the last rotation. A token refresh is committed by the answerer while it
      is still handling the request, so a response lost on the way back would otherwise break both directions at
      once. Keeping the superseded token acceptable for a bounded window lets the initiator retry with either token
      until one reply completes the rotation.""")
  @Column(name = "token_this_previous")
  private String tokenThisPrevious;

  @JsonIgnore
  @Schema(description = """
      UTC instant after which tokenThisPrevious is no longer accepted. Null when no rotation has happened or the
      overlap has been cleared.""")
  @Column(name = "token_this_previous_valid_until")
  private LocalDateTime tokenThisPreviousValidUntil;

  @Override
  public Integer getId() {
    return idGtNet;
  }

  public Integer getIdGtNet() {
    return idGtNet;
  }

  public void setIdGtNet(Integer idGtNet) {
    this.idGtNet = idGtNet;
  }

  public Integer getDailyRequestLimitCount() {
    return dailyRequestLimitCount;
  }

  public void setDailyRequestLimitCount(Integer dailyRequestLimitCount) {
    this.dailyRequestLimitCount = dailyRequestLimitCount;
  }

  public String getTokenThis() {
    return tokenThis;
  }

  public void setTokenThis(String tokenThis) {
    this.tokenThis = tokenThis;
  }

  public String getTokenRemote() {
    return tokenRemote;
  }

  public void setTokenRemote(String tokenRemote) {
    this.tokenRemote = tokenRemote;
  }

  public Integer getDailyRequestLimitRemoteCount() {
    return dailyRequestLimitRemoteCount;
  }

  public void setDailyRequestLimitRemoteCount(Integer dailyRequestLimitRemoteCount) {
    this.dailyRequestLimitRemoteCount = dailyRequestLimitRemoteCount;
  }

  public LocalDate getDailyRequestLimitDate() {
    return dailyRequestLimitDate;
  }

  public void setDailyRequestLimitDate(LocalDate dailyRequestLimitDate) {
    this.dailyRequestLimitDate = dailyRequestLimitDate;
  }

  public LocalDateTime getSupplierLastUpdate() {
    return supplierLastUpdate;
  }

  public void setSupplierLastUpdate(LocalDateTime supplierLastUpdate) {
    this.supplierLastUpdate = supplierLastUpdate;
  }

  public boolean isAuthorizedRemoteEntry() {
    return tokenThis != null && tokenRemote != null;
  }

  public String getTokenThisPrevious() {
    return tokenThisPrevious;
  }

  public void setTokenThisPrevious(String tokenThisPrevious) {
    this.tokenThisPrevious = tokenThisPrevious;
  }

  public LocalDateTime getTokenThisPreviousValidUntil() {
    return tokenThisPreviousValidUntil;
  }

  public void setTokenThisPreviousValidUntil(LocalDateTime tokenThisPreviousValidUntil) {
    this.tokenThisPreviousValidUntil = tokenThisPreviousValidUntil;
  }

  /**
   * Whether the superseded token is still inside its overlap window and may therefore still authenticate a peer that
   * has not learned the new one yet.
   *
   * @param now the current UTC instant
   * @return true when a previous token exists and its window has not passed
   */
  public boolean isPreviousTokenValid(LocalDateTime now) {
    return tokenThisPrevious != null && tokenThisPreviousValidUntil != null
        && now.isBefore(tokenThisPreviousValidUntil);
  }

  public boolean isServerlistAccessGranted() {
    return serverlistAccessGranted;
  }

  public void setServerlistAccessGranted(boolean serverlistAccessGranted) {
    this.serverlistAccessGranted = serverlistAccessGranted;
  }

  public Byte getRequestViolationCount() {
    return requestViolationCount;
  }

  public void setRequestViolationCount(Byte requestViolationCount) {
    this.requestViolationCount = requestViolationCount;
  }

  /**
   * Increments the request violation counter. Initializes to 1 if currently null. Caps at 99.
   */
  public void incrementRequestViolationCount() {
    if (this.requestViolationCount == null) {
      this.requestViolationCount = 1;
    } else if (this.requestViolationCount < 99) {
      this.requestViolationCount = (byte) (this.requestViolationCount + 1);
    }
  }

  public Byte getConnectionTimeout() {
    return connectionTimeout;
  }

  public void setConnectionTimeout(Byte connectionTimeout) {
    this.connectionTimeout = connectionTimeout;
  }

  public LocalDateTime getHandshakeTimestamp() {
    return handshakeTimestamp;
  }

  public void setHandshakeTimestamp(LocalDateTime handshakeTimestamp) {
    this.handshakeTimestamp = handshakeTimestamp;
  }

  public LocalDateTime getReconnectRequestedTime() {
    return reconnectRequestedTime;
  }

  public void setReconnectRequestedTime(LocalDateTime reconnectRequestedTime) {
    this.reconnectRequestedTime = reconnectRequestedTime;
  }
}
