package grafioschtrader.gtnet.model;

import java.util.List;
import java.util.Map;

import grafioschtrader.entities.GTNetMessage.GTNetMessageParam;
import grafioschtrader.gtnet.GTNetMessageCodeType;
import io.swagger.v3.oas.annotations.media.Schema;

public class MsgRequest {
  @Schema(description = "ID's of the target remote machines")
  public List<Integer> idGTNetTargetDomains;

  @Schema(description = "Used if this message refers to a previous one")
  public Integer replyTo;
  
  @Schema(description = "If the messages are generated by the system, then a code is transmitted")
  public GTNetMessageCodeType messageCode;
  
  public Map<String, GTNetMessageParam> gtNetMessageParamMap;
  
  @Schema(description = "Contains optional a message. This message is mostly created by the user")
  public String message; 
}
