package grafioschtrader.entities;

import java.io.Serializable;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import grafiosch.BaseConstants;
import grafiosch.entities.TenantBaseID;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity for the {@code algo_message_alert} table. Stores alarm records generated by the alarm evaluation system
 * when alert conditions on strategies or watchlist securities are triggered. Each record captures the alarm type,
 * structured JSON details about the condition that fired, and the time of triggering. Used by both Tier 1
 * (event-driven simple alerts) and Tier 2 (scheduled indicator alerts).
 */
@Schema(description = """
    Alarm record created when a strategy alert condition triggers. Captures the alarm type, security context,
    triggering details as JSON, and optional link to the recommendation that caused the alert.""")
@Entity
@Table(name = AlgoMessageAlert.TABNAME)
public class AlgoMessageAlert extends TenantBaseID implements Serializable {

  public static final String TABNAME = "algo_message_alert";

  private static final long serialVersionUID = 1L;

  @Schema(description = "Auto-generated primary key")
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Basic(optional = false)
  @Column(name = "id_algo_message_alert")
  private Integer idAlgoMessageAlert;

  @Schema(description = "Security or currency pair that triggered the alarm. Null for portfolio-level alerts.")
  @Column(name = "id_security_currency")
  private Integer idSecurityCurrency;

  @Schema(description = "Owning tenant")
  @Basic(optional = false)
  @Column(name = "id_tenant")
  private Integer idTenant;

  @Schema(description = "Strategy whose condition was evaluated and triggered this alarm")
  @Basic(optional = false)
  @Column(name = "id_algo_strategy")
  private Integer idAlgoStrategy;

  @Schema(description = "Timestamp when the alarm condition was detected")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = BaseConstants.STANDARD_DATE_TIME_FORMAT)
  @Column(name = "alert_time")
  private LocalDateTime alertTime;

  @Schema(description = """
      Numeric alarm type code. Values: 1=PRICE_ALERT, 2=ENTRY_SIGNAL, 3=PROFIT_TAKE, 4=STOP_LOSS,
      5=REBALANCE_DRIFT, 6=RISK_BREACH. Corresponds to the strategy implementation type that fired.""")
  @Column(name = "alarm_type")
  private Byte alarmType;

  @Schema(description = """
      Structured JSON with details about the triggered condition. Structure depends on alarm type, e.g.
      {"threshold": 150.0, "actual": 152.3, "direction": "ABOVE"} for a price alert or
      {"rsiValue": 28.5, "lowerThreshold": 30} for an RSI threshold alert.""")
  @Column(name = "alarm_details", columnDefinition = "JSON")
  private String alarmDetails;

  @Schema(description = "Optional link to the recommendation that triggered this alarm. Null for standalone alerts.")
  @Column(name = "id_algo_recommendation")
  private Integer idAlgoRecommendation;

  @JsonIgnore
  @Override
  public Integer getId() {
    return idAlgoMessageAlert;
  }

  public Integer getIdAlgoMessageAlert() {
    return idAlgoMessageAlert;
  }

  public void setIdAlgoMessageAlert(Integer idAlgoMessageAlert) {
    this.idAlgoMessageAlert = idAlgoMessageAlert;
  }

  public Integer getIdSecurityCurrency() {
    return idSecurityCurrency;
  }

  public void setIdSecurityCurrency(Integer idSecurityCurrency) {
    this.idSecurityCurrency = idSecurityCurrency;
  }

  @Override
  public Integer getIdTenant() {
    return idTenant;
  }

  @Override
  public void setIdTenant(Integer idTenant) {
    this.idTenant = idTenant;
  }

  public Integer getIdAlgoStrategy() {
    return idAlgoStrategy;
  }

  public void setIdAlgoStrategy(Integer idAlgoStrategy) {
    this.idAlgoStrategy = idAlgoStrategy;
  }

  public LocalDateTime getAlertTime() {
    return alertTime;
  }

  public void setAlertTime(LocalDateTime alertTime) {
    this.alertTime = alertTime;
  }

  public Byte getAlarmType() {
    return alarmType;
  }

  public void setAlarmType(Byte alarmType) {
    this.alarmType = alarmType;
  }

  public String getAlarmDetails() {
    return alarmDetails;
  }

  public void setAlarmDetails(String alarmDetails) {
    this.alarmDetails = alarmDetails;
  }

  public Integer getIdAlgoRecommendation() {
    return idAlgoRecommendation;
  }

  public void setIdAlgoRecommendation(Integer idAlgoRecommendation) {
    this.idAlgoRecommendation = idAlgoRecommendation;
  }
}
