package grafioschtrader.entities;

import java.io.Serializable;
import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonIgnore;

import grafiosch.entities.TenantBaseID;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Size;

/**
 * Trading signals and rebalancing recommendations generated by strategy evaluation or simulation. Lifecycle: a
 * recommendation is created with a type, target units, and price; once the user acts on it (or the simulation
 * auto-executes), {@code executedAt} is set and {@code idTransaction} links to the resulting transaction.
 */
@Schema(description = """
    Trading signal or rebalancing recommendation. Lifecycle: created with target units and price, then
    optionally linked to an executed transaction via executedAt and idTransaction.""")
@Entity
@Table(name = AlgoRecommendation.TABNAME)
public class AlgoRecommendation extends TenantBaseID implements Serializable {

  public static final String TABNAME = "algo_recommendation";

  private static final long serialVersionUID = 1L;

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Basic(optional = false)
  @Column(name = "id_algo_recommendation")
  private Integer idAlgoRecommendation;

  @Basic(optional = false)
  @Column(name = "id_tenant")
  private Integer idTenant;

  @Basic(optional = false)
  @Column(name = "id_algo_assetclass_security")
  private Integer idAlgoAssetclassSecurity;

  @Basic(optional = false)
  @Column(name = "id_securitycurrency")
  private Integer idSecuritycurrency;

  @Schema(description = "Recommendation type: 1=BUY, 2=SELL, 3=HOLD, 4=REBALANCE")
  @Basic(optional = false)
  @Column(name = "recommendation_type")
  private Byte recommendationType;

  @Schema(description = "Suggested number of units to buy or sell")
  @Column(name = "recommended_units")
  private Double recommendedUnits;

  @Schema(description = "Target price at which the action should be executed")
  @Column(name = "recommended_price")
  private Double recommendedPrice;

  @Schema(description = "Human-readable explanation of why this recommendation was generated")
  @Size(max = 500)
  @Column(name = "rationale")
  private String rationale;

  @Schema(description = "Auto-maintained timestamp when the recommendation was created")
  @Column(name = "created_at", insertable = false, updatable = false)
  private Timestamp createdAt;

  @Schema(description = "Timestamp when the recommendation was acted upon. Null while pending.")
  @Column(name = "executed_at")
  private Timestamp executedAt;

  @Schema(description = "Foreign key to the transaction created when this recommendation was executed. Null while pending.")
  @Column(name = "id_transaction")
  private Integer idTransaction;

  @JsonIgnore
  @Override
  public Integer getId() {
    return idAlgoRecommendation;
  }

  public Integer getIdAlgoRecommendation() {
    return idAlgoRecommendation;
  }

  public void setIdAlgoRecommendation(Integer idAlgoRecommendation) {
    this.idAlgoRecommendation = idAlgoRecommendation;
  }

  @Override
  public Integer getIdTenant() {
    return idTenant;
  }

  @Override
  public void setIdTenant(Integer idTenant) {
    this.idTenant = idTenant;
  }

  public Integer getIdAlgoAssetclassSecurity() {
    return idAlgoAssetclassSecurity;
  }

  public void setIdAlgoAssetclassSecurity(Integer idAlgoAssetclassSecurity) {
    this.idAlgoAssetclassSecurity = idAlgoAssetclassSecurity;
  }

  public Integer getIdSecuritycurrency() {
    return idSecuritycurrency;
  }

  public void setIdSecuritycurrency(Integer idSecuritycurrency) {
    this.idSecuritycurrency = idSecuritycurrency;
  }

  public Byte getRecommendationType() {
    return recommendationType;
  }

  public void setRecommendationType(Byte recommendationType) {
    this.recommendationType = recommendationType;
  }

  public Double getRecommendedUnits() {
    return recommendedUnits;
  }

  public void setRecommendedUnits(Double recommendedUnits) {
    this.recommendedUnits = recommendedUnits;
  }

  public Double getRecommendedPrice() {
    return recommendedPrice;
  }

  public void setRecommendedPrice(Double recommendedPrice) {
    this.recommendedPrice = recommendedPrice;
  }

  public String getRationale() {
    return rationale;
  }

  public void setRationale(String rationale) {
    this.rationale = rationale;
  }

  public Timestamp getCreatedAt() {
    return createdAt;
  }

  public Timestamp getExecutedAt() {
    return executedAt;
  }

  public void setExecutedAt(Timestamp executedAt) {
    this.executedAt = executedAt;
  }

  public Integer getIdTransaction() {
    return idTransaction;
  }

  public void setIdTransaction(Integer idTransaction) {
    this.idTransaction = idTransaction;
  }
}
