package grafioschtrader.entities;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

import grafiosch.BaseConstants;
import grafiosch.entities.TenantBaseID;
import grafioschtrader.types.AlgoSignalKind;
import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity for the {@code algo_message_alert} table. Stores alarm records generated by the alarm evaluation system
 * when alert conditions on strategies or watchlist securities are triggered. Each record captures the signal kind,
 * structured JSON details about the condition that fired, and the time of triggering. Used by both Tier 1 (event-driven
 * simple alerts) and Tier 2 (scheduled indicator alerts).
 *
 * <p>
 * The columns {@code idTenant}, {@code idAlgoStrategy}, {@code idSecurityCurrency}, {@code alarmType},
 * {@code signalDirection}, {@code trancheKey} and {@code alertDay} together form the signal identity and carry the
 * unique key {@code UK_AlarmDay}. That key <em>is</em> the daily deduplication: an insert that violates it means the
 * same signal was already reported today. All seven are therefore non-null, with 0 standing for "no instrument" and "no
 * direction" and the empty string for "no tranche" - a nullable column would be distinct from itself in a MariaDB
 * unique index and would let the same alarm be written without limit.
 * </p>
 */
@Entity
@Table(name = AlgoMessageAlert.TABNAME)
public class AlgoMessageAlert extends TenantBaseID implements Serializable {

  public static final String TABNAME = "algo_message_alert";

  private static final long serialVersionUID = 1L;

  /** Sentinel for the instrument column when a signal is not about a single instrument. */
  public static final Integer NO_SECURITY = 0;

  /** Sentinel for the direction column when a signal has no direction. */
  public static final byte NO_DIRECTION = 0;

  /** Sentinel for the tranche column when a signal belongs to no profit taking tranche. */
  public static final String NO_TRANCHE = "";

  /** Auto-generated primary key. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Basic(optional = false)
  @Column(name = "id_algo_message_alert")
  private Integer idAlgoMessageAlert;

  /** Instrument that triggered the alarm. 0 when the signal is not about a single instrument. */
  @Basic(optional = false)
  @Column(name = "id_security_currency")
  private Integer idSecurityCurrency = NO_SECURITY;

  /** Owning tenant. */
  @Basic(optional = false)
  @Column(name = "id_tenant")
  private Integer idTenant;

  /** Strategy whose condition was evaluated and triggered this alarm. */
  @Basic(optional = false)
  @Column(name = "id_algo_strategy")
  private Integer idAlgoStrategy;

  /** Timestamp when the alarm condition was detected. */
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = BaseConstants.STANDARD_DATE_TIME_FORMAT)
  @Column(name = "alert_time")
  private LocalDateTime alertTime;

  /** Kind of signal that fired, see {@link AlgoSignalKind}. */
  @Basic(optional = false)
  @Column(name = "alarm_type")
  private byte alarmType;

  /**
   * Direction of the crossing: -1 downward, 1 upward, 0 when the signal has no direction. The two bounds of one alert
   * are separate signals, so an instrument may notify on both on the same day.
   */
  @Basic(optional = false)
  @Column(name = "signal_direction")
  private byte signalDirection = NO_DIRECTION;

  /** Identifies one profit taking tranche. Empty for every alert signal. */
  @Basic(optional = false)
  @Column(name = "tranche_key")
  private String trancheKey = NO_TRANCHE;

  /** Application day of the alarm, the unit of daily deduplication. */
  @JsonFormat(pattern = BaseConstants.STANDARD_DATE_FORMAT)
  @Basic(optional = false)
  @Column(name = "alert_day")
  private LocalDate alertDay;

  /**
   * Structured JSON with details about the triggered condition. Its structure depends on the alarm type, for example a
   * threshold and actual price for a price alert, or an RSI value and lower threshold for an RSI alert.
   */
  @Column(name = "alarm_details", columnDefinition = "JSON")
  private String alarmDetails;

  /**
   * Status of the durable notification delivery. The alarm is claimed once by its unique key, and delivery is retried
   * against that claim rather than raising a second one; the completion time of each channel is kept in
   * {@code internalCompletedAt} and {@code externalCompletedAt}.
   */
  @Column(name = "delivery_status")
  private String deliveryStatus = "PENDING";

  public String getDeliveryStatus() {
    return deliveryStatus;
  }

  public void setDeliveryStatus(String value) {
    this.deliveryStatus = value;
  }

  /** User receiving the durable notification. */
  @Column(name = "recipient_user_id")
  private Integer recipientUserId;

  public Integer getRecipientUserId() {
    return recipientUserId;
  }

  public void setRecipientUserId(Integer value) {
    this.recipientUserId = value;
  }

  /** Email address receiving the durable notification. */
  @Column(name = "recipient_email")
  private String recipientEmail;

  public String getRecipientEmail() {
    return recipientEmail;
  }

  public void setRecipientEmail(String value) {
    this.recipientEmail = value;
  }

  /** Channels selected for the durable notification delivery. */
  @Column(name = "delivery_channels")
  private String deliveryChannels;

  public String getDeliveryChannels() {
    return deliveryChannels;
  }

  public void setDeliveryChannels(String value) {
    this.deliveryChannels = value;
  }

  /** Subject captured for the durable notification delivery. */
  @Column(name = "delivery_subject")
  private String deliverySubject;

  public String getDeliverySubject() {
    return deliverySubject;
  }

  public void setDeliverySubject(String value) {
    this.deliverySubject = value;
  }

  /** Body captured for the durable notification delivery. */
  @Column(name = "delivery_body")
  private String deliveryBody;

  public String getDeliveryBody() {
    return deliveryBody;
  }

  public void setDeliveryBody(String value) {
    this.deliveryBody = value;
  }

  /** Time at which internal delivery completed. */
  @Column(name = "internal_completed_at")
  @JsonFormat(pattern = BaseConstants.STANDARD_LOCAL_DATE_TIME_SECOND)
  private LocalDateTime internalCompletedAt;

  public LocalDateTime getInternalCompletedAt() {
    return internalCompletedAt;
  }

  public void setInternalCompletedAt(LocalDateTime value) {
    this.internalCompletedAt = value;
  }

  /** Time at which external delivery completed. */
  @Column(name = "external_completed_at")
  @JsonFormat(pattern = BaseConstants.STANDARD_LOCAL_DATE_TIME_SECOND)
  private LocalDateTime externalCompletedAt;

  public LocalDateTime getExternalCompletedAt() {
    return externalCompletedAt;
  }

  public void setExternalCompletedAt(LocalDateTime value) {
    this.externalCompletedAt = value;
  }

  /** Number of delivery attempts. */
  @Column(name = "delivery_attempts")
  private int deliveryAttempts;

  public int getDeliveryAttempts() {
    return deliveryAttempts;
  }

  public void setDeliveryAttempts(int value) {
    this.deliveryAttempts = value;
  }

  /** Earliest time for the next delivery attempt. */
  @Column(name = "next_attempt_at")
  @JsonFormat(pattern = BaseConstants.STANDARD_LOCAL_DATE_TIME_SECOND)
  private LocalDateTime nextAttemptAt;

  public LocalDateTime getNextAttemptAt() {
    return nextAttemptAt;
  }

  public void setNextAttemptAt(LocalDateTime value) {
    this.nextAttemptAt = value;
  }

  /** Error from the latest delivery attempt. */
  @Column(name = "delivery_error")
  private String deliveryError;

  public String getDeliveryError() {
    return deliveryError;
  }

  public void setDeliveryError(String value) {
    this.deliveryError = value;
  }

  /** Token identifying the worker that holds the delivery lease. */
  @Column(name = "delivery_lease_token")
  private String deliveryLeaseToken;

  public String getDeliveryLeaseToken() {
    return deliveryLeaseToken;
  }

  public void setDeliveryLeaseToken(String value) {
    this.deliveryLeaseToken = value;
  }

  /** Time until which the delivery lease is valid. */
  @Column(name = "delivery_lease_until")
  @JsonFormat(pattern = BaseConstants.STANDARD_LOCAL_DATE_TIME_SECOND)
  private LocalDateTime deliveryLeaseUntil;

  public LocalDateTime getDeliveryLeaseUntil() {
    return deliveryLeaseUntil;
  }

  public void setDeliveryLeaseUntil(LocalDateTime value) {
    this.deliveryLeaseUntil = value;
  }

  /** Display name of the context captured when the notification was created. */
  @Column(name = "context_name")
  private String contextName;

  public String getContextName() {
    return contextName;
  }

  public void setContextName(String value) {
    this.contextName = value;
  }

  /** Display name of the security captured when the notification was created. */
  @Column(name = "security_name")
  private String securityName;

  public String getSecurityName() {
    return securityName;
  }

  public void setSecurityName(String value) {
    this.securityName = value;
  }

  @JsonIgnore
  @Override
  public Integer getId() {
    return idAlgoMessageAlert;
  }

  public Integer getIdAlgoMessageAlert() {
    return idAlgoMessageAlert;
  }

  public void setIdAlgoMessageAlert(Integer idAlgoMessageAlert) {
    this.idAlgoMessageAlert = idAlgoMessageAlert;
  }

  public Integer getIdSecurityCurrency() {
    return idSecurityCurrency;
  }

  public void setIdSecurityCurrency(Integer idSecurityCurrency) {
    this.idSecurityCurrency = idSecurityCurrency;
  }

  @Override
  public Integer getIdTenant() {
    return idTenant;
  }

  @Override
  public void setIdTenant(Integer idTenant) {
    this.idTenant = idTenant;
  }

  public Integer getIdAlgoStrategy() {
    return idAlgoStrategy;
  }

  public void setIdAlgoStrategy(Integer idAlgoStrategy) {
    this.idAlgoStrategy = idAlgoStrategy;
  }

  public LocalDateTime getAlertTime() {
    return alertTime;
  }

  public void setAlertTime(LocalDateTime alertTime) {
    this.alertTime = alertTime;
  }

  public AlgoSignalKind getAlarmType() {
    return AlgoSignalKind.getAlgoSignalKindByValue(this.alarmType);
  }

  public void setAlarmType(AlgoSignalKind alarmType) {
    this.alarmType = alarmType.getValue();
  }

  public byte getSignalDirection() {
    return signalDirection;
  }

  public void setSignalDirection(byte signalDirection) {
    this.signalDirection = signalDirection;
  }

  public String getTrancheKey() {
    return trancheKey;
  }

  public void setTrancheKey(String trancheKey) {
    this.trancheKey = trancheKey;
  }

  public LocalDate getAlertDay() {
    return alertDay;
  }

  public void setAlertDay(LocalDate alertDay) {
    this.alertDay = alertDay;
  }

  public String getAlarmDetails() {
    return alarmDetails;
  }

  public void setAlarmDetails(String alarmDetails) {
    this.alarmDetails = alarmDetails;
  }

}
