package grafioschtrader.entities;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import grafiosch.entities.BaseID;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;


@Schema(description = """
This GTNet configuration contains the general configuration and is not transferred externally.
Once a successful handshake has been made with a GT instance, such an entity is created.""")
@Entity
@Table(name = GTNetConfig.TABNAME)
public class GTNetConfig extends BaseID<Integer>  {

  public static final String TABNAME = "gt_net_config";
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id_gt_net_config")
  private Integer idGtNetConfig;

  @Schema(description = "Reference to the parent GTNet domain entry")
  @Column(name = "id_gt_net", nullable = false, insertable = false, updatable = false)
  private Integer idGtNet;
  
  @Schema(description = "Collection of entity-specific configurations for exchange settings per data type")
  @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL, orphanRemoval = true)
  @JoinColumn(name = "id_gt_net_config")
  private List<GTNetConfigEntity> gtNetConfigEntities = new ArrayList<>();

  @JsonIgnore
  @Schema(description = """
      Authentication token generated by this server during the first handshake. This token is sent to the remote
      domain and stored there as tokenRemote. The remote domain must include this token in the Authorization header
      when making requests to this server. Marked @JsonIgnore to prevent accidental exposure via REST API.""")
  @Column(name = "token_this")
  private String tokenThis;

  @JsonIgnore
  @Schema(description = """
      Authentication token received from the remote domain during the first handshake. This token must be included
      in the Authorization header when this server makes requests to the remote domain. Marked @JsonIgnore to
      prevent accidental exposure via REST API. Set to null if the handshake has not been completed.""")
  @Column(name = "token_remote")
  private String tokenRemote;

  @Schema(description = """
      Current count of requests received from the remote domain today. Incremented with each incoming request and
      compared against dailyRequestLimit to enforce rate limiting. Automatically reset to null at UTC 00:00 by a
      scheduled background job.""")
  @Column(name = "daily_req_limit_count")
  private Integer dailyRequestLimitCount;
  
  @Schema(description = """
      Current count of requests this server has made to the remote domain today. Used to self-limit outgoing
      requests before hitting the remote's rate limit. Automatically reset to null at UTC 00:00 by a scheduled
      background job.""")
  @Column(name = "daily_req_limit_remote_count")
  private Integer dailyRequestLimitRemoteCount;

  @Override
  public Integer getId() {
    return idGtNetConfig;
  }


  public Integer getIdGtNet() {
	return idGtNet;
}


  public void setIdGtNet(Integer idGtNet) {
	this.idGtNet = idGtNet;
  }


  public Integer getDailyRequestLimitCount() {
    return dailyRequestLimitCount;
  }


  public List<GTNetConfigEntity> getGtNetConfigEntities() {
    return gtNetConfigEntities;
  }

  public void setGtNetConfigEntities(List<GTNetConfigEntity> gtNetConfigEntities) {
    this.gtNetConfigEntities = gtNetConfigEntities;
  }

  public void setDailyRequestLimitCount(Integer dailyRequestLimitCount) {
    this.dailyRequestLimitCount = dailyRequestLimitCount;
  }

  public Integer getIdGtNetConfig() {
    return idGtNetConfig;
  }

  public String getTokenThis() {
    return tokenThis;
  }

  public void setTokenThis(String tokenThis) {
    this.tokenThis = tokenThis;
  }

  public String getTokenRemote() {
    return tokenRemote;
  }

  public void setTokenRemote(String tokenRemote) {
    this.tokenRemote = tokenRemote;
  }

  public Integer getDailyRequestLimitRemoteCount() {
    return dailyRequestLimitRemoteCount;
  }

  public void setDailyRequestLimitRemoteCount(Integer dailyRequestLimitRemoteCount) {
    this.dailyRequestLimitRemoteCount = dailyRequestLimitRemoteCount;
  }

  /**
   * Gets or creates a GTNetConfigEntity for the specified GTNetEntity.
   *
   * @param idGtNetEntity the ID of the associated GTNetEntity
   * @return the existing or newly created GTNetConfigEntity
   */
  public GTNetConfigEntity getOrCreateConfigEntity(Integer idGtNetEntity) {
    return gtNetConfigEntities.stream()
        .filter(e -> idGtNetEntity.equals(e.getIdGtNetEntity()))
        .findFirst()
        .orElseGet(() -> {
          GTNetConfigEntity newConfigEntity = new GTNetConfigEntity();
          newConfigEntity.setIdGtNetConfig(this.idGtNetConfig);
          newConfigEntity.setIdGtNetEntity(idGtNetEntity);
          gtNetConfigEntities.add(newConfigEntity);
          return newConfigEntity;
        });
  }
}
