package grafioschtrader.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import grafioschtrader.types.GTNetMessageCodeTypes;
import grafioschtrader.types.SendReceivedType;
import io.swagger.v3.oas.annotations.media.Schema;

@Entity
@Table(name = GTNetMessage.TABNAME)
@Schema(description = """
    This entity records the basic messages between the instances of the GT network.
    In addition, these messages are also used to communicate between the GT instances.""")
public class GTNetMessage extends BaseID {

  public static final String TABNAME = "gt_net_message";

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id_gt_net_message")
  private Integer idGtNetMessage;

  @Schema(description = "Connection to GTNet")
  @Column(name = "id_gt_net")
  private Integer idGtNet;

  @Schema(description = "When was this message created. It must be UTC Time")
  @Column(name = "timestamp")
  @Temporal(TemporalType.TIMESTAMP)
  private Date timestamp;

  @Schema(description = "Distinguish whether the message was sent or received")
  @Column(name = "send_recv")
  private byte sendRecv;

  @Schema(description = "Used if this message refers to a previous one")
  @Column(name = "reply_to")
  private Integer replyTo;

  @Schema(description = "If the messages are generated by the system, then a code is transmitted")
  @Column(name = "message_code")
  private Short messageCode;

  @Schema(description = "Contains optional a message")
  @Column(name = "message")
  private String message;

  public Integer getIdGtNetMessage() {
    return idGtNetMessage;
  }

  public void setIdGtNetMessage(Integer idGtNetMessage) {
    this.idGtNetMessage = idGtNetMessage;
  }

  public Integer getIdGtNet() {
    return idGtNet;
  }

  public void setIdGtNet(Integer idGtNet) {
    this.idGtNet = idGtNet;
  }
  

  public Date getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Date timestamp) {
    this.timestamp = timestamp;
  }

  public SendReceivedType getSendRecv() {
    return SendReceivedType.getSendReceivedType(sendRecv);
  }

  public void setSendRecv(SendReceivedType sendReceivedType) {
    this.sendRecv = sendReceivedType.getValue();
  }

  public Integer getReplyTo() {
    return replyTo;
  }

  public void setReplyTo(Integer replyTo) {
    this.replyTo = replyTo;
  }

  public GTNetMessageCodeTypes getMessageCode() {
    return GTNetMessageCodeTypes.getGTNetMessageCodeTypes(messageCode);
  }

  public void setMessageCode(GTNetMessageCodeTypes gtNetMessageCodeTypes) {
    this.messageCode = gtNetMessageCodeTypes.getValue();
  }

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  @Override
  public Integer getId() {
    return idGtNetMessage;
  }

}
