package grafioschtrader.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import grafiosch.common.PropertyAlwaysUpdatable;
import grafiosch.entities.BaseID;
import grafioschtrader.gtnet.GTNetExchangeStatusTypes;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;


@Schema(description = """
This GTNet configuration contains the general configuration and is not transferred externally.
Once a successful handshake has been made with a GT instance, such an entity is created.""")
@Entity
@Table(name = GTNetConfig.TABNAME)
public class GTNetConfig extends BaseID<Integer>  {

  public static final String TABNAME = "gt_net_config";
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id_gt_net_config")
  private Integer idGtNetConfig;

  @JsonIgnore
  @Schema(description = """
      Authentication token generated by this server during the first handshake. This token is sent to the remote
      domain and stored there as tokenRemote. The remote domain must include this token in the Authorization header
      when making requests to this server. Marked @JsonIgnore to prevent accidental exposure via REST API.""")
  @Column(name = "token_this")
  private String tokenThis;

  @JsonIgnore
  @Schema(description = """
      Authentication token received from the remote domain during the first handshake. This token must be included
      in the Authorization header when this server makes requests to the remote domain. Marked @JsonIgnore to
      prevent accidental exposure via REST API. Set to null if the handshake has not been completed.""")
  @Column(name = "token_remote")
  private String tokenRemote;

  @Schema(description = """
      Current count of requests received from the remote domain today. Incremented with each incoming request and
      compared against dailyRequestLimit to enforce rate limiting. Automatically reset to null at UTC 00:00 by a
      scheduled background job.""")
  @Column(name = "daily_req_limit_count")
  private Integer dailyRequestLimitCount;
  
  @Schema(description = """
      Current count of requests this server has made to the remote domain today. Used to self-limit outgoing
      requests before hitting the remote's rate limit. Automatically reset to null at UTC 00:00 by a scheduled
      background job.""")
  @Column(name = "daily_req_limit_remote_count")
  private Integer dailyRequestLimitRemoteCount;

  @Schema(description = """
      Enables detailed logging of intraday price updates from this remote domain. When true, each price change is
      recorded in GTNetLastpriceDetailLog, providing an audit trail of which client changed which prices and when.
      May impact performance when enabled for high-volume providers.""")
  @Column(name = "lastprice_use_detail_log")
  @PropertyAlwaysUpdatable
  private boolean lastpriceUseDetailLog;

  @Schema(description = """
      Exchange status for intraday/last price data with this remote instance. Determines the direction of
      data flow: no exchange (0), send only (1), receive only (2), or bidirectional (3). Updated when
      lastprice exchange requests are accepted.""")
  @Column(name = "lastprice_exchange")
  private byte lastpriceExchange;

  @Schema(description = """
      Exchange status for entity/historical data with this remote instance. Determines the direction of
      data flow: no exchange (0), send only (1), receive only (2), or bidirectional (3). Updated when
      entity exchange requests are accepted.""")
  @Column(name = "entity_exchange")
  private byte entityExchange;
  
  
  @Schema(description = """
      Priority level for using this remote domain as an intraday price provider. Value 0 means this provider is
      not used. Values greater than 0 indicate priority (lower numbers = higher priority). Multiple providers can
      be configured with different priorities for failover scenarios.""")
  @Column(name = "lastprice_consumer_usage")
  private byte lastpriceConsumerUsage;
  
  
  @Override
  public Integer getId() {
    return idGtNetConfig;
  }


  public Integer getDailyRequestLimitCount() {
    return dailyRequestLimitCount;
  }


  public void setDailyRequestLimitCount(Integer dailyRequestLimitCount) {
    this.dailyRequestLimitCount = dailyRequestLimitCount;
  }


  public boolean isLastpriceUseDetailLog() {
    return lastpriceUseDetailLog;
  }


  public void setLastpriceUseDetailLog(boolean lastpriceUseDetailLog) {
    this.lastpriceUseDetailLog = lastpriceUseDetailLog;
  }


  public Integer getIdGtNetConfig() {
    return idGtNetConfig;
  }

  public String getTokenThis() {
    return tokenThis;
  }

  public void setTokenThis(String tokenThis) {
    this.tokenThis = tokenThis;
  }

  public String getTokenRemote() {
    return tokenRemote;
  }

  public void setTokenRemote(String tokenRemote) {
    this.tokenRemote = tokenRemote;
  }

  @JsonProperty("lastpriceExchange")
  public GTNetExchangeStatusTypes getLastpriceExchange() {
    return GTNetExchangeStatusTypes.getGTNetExchangeStatusType(lastpriceExchange);
  }

  @JsonProperty("lastpriceExchange")
  public void setLastpriceExchange(GTNetExchangeStatusTypes lastpriceExchange) {
    this.lastpriceExchange = lastpriceExchange.getValue();
  }

  @JsonProperty("entityExchange")
  public GTNetExchangeStatusTypes getEntityExchange() {
    return GTNetExchangeStatusTypes.getGTNetExchangeStatusType(entityExchange);
  }

  @JsonProperty("entityExchange")
  public void setEntityExchange(GTNetExchangeStatusTypes entityExchange) {
    this.entityExchange = entityExchange.getValue();
  }

  public byte getLastpriceConsumerUsage() {
    return lastpriceConsumerUsage;
  }

  public void setLastpriceConsumerUsage(byte lastpriceConsumerUsage) {
    this.lastpriceConsumerUsage = lastpriceConsumerUsage;
  }
  
  public Integer getDailyRequestLimitRemoteCount() {
    return dailyRequestLimitRemoteCount;
  }

  public void setDailyRequestLimitRemoteCount(Integer dailyRequestLimitRemoteCount) {
    this.dailyRequestLimitRemoteCount = dailyRequestLimitRemoteCount;
  }

  
}
