package grafioschtrader.entities;

import java.io.Serializable;

import grafiosch.entities.BaseID;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Basic;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Schema(description = """
    Is generated by the system and is used to log the error if the import was not successful for a transaction.
    A distinction must be made as to whether a CSV, TXT or PDF file was imported.
    For CSV, the import template is selected; for PDF, the import template is specified.
    This means that the import template for PDF has a high information content in the error display.""")
@Entity
@Table(name = ImportTransactionPosFailed.TABNAME)
public class ImportTransactionPosFailed extends BaseID<Integer> implements Serializable {

  public static final String TABNAME = "imp_trans_pos_failed";

  private static final long serialVersionUID = 1L;

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Basic(optional = false)
  @Column(name = "id_imp_trans_pos_failed")
  private Integer idTransactionPosFailed;

  @Schema(description = "Reference to the import template")
  @Column(name = "id_trans_imp_template")
  private Integer idTransactionImportTemplate;

  @Schema(description = """
      Contains the last successfully parsed property.
      This provides a reference to where the correction should be made to the data or the import template.""")
  @Column(name = "last_matching_property")
  private String lastMatchingProperty;

  @Schema(description = "Reference to import transaction position")
  @Column(name = "id_trans_pos")
  private Integer idTransactionPos;

  @Schema(description = "Contains the possible error that occurred when parsing a single line of a CSV file.")
  @Column(name = "error_message")
  private String errorMessage;

  public ImportTransactionPosFailed() {
    super();
  }

  public ImportTransactionPosFailed(Integer idTransactionPos, Integer idTransactionImportTemplate,
      String lastMatchingProperty) {
    this.idTransactionPos = idTransactionPos;
    this.idTransactionImportTemplate = idTransactionImportTemplate;
    this.lastMatchingProperty = lastMatchingProperty;
  }

  public ImportTransactionPosFailed(Integer idTransactionPos, Integer idTransactionImportTemplate,
      String lastMatchingProperty, String errorMessage) {
    this(idTransactionPos, idTransactionImportTemplate, lastMatchingProperty);
    this.errorMessage = errorMessage;
  }

  public Integer getIdTransactionPosFailed() {
    return idTransactionPosFailed;
  }

  public Integer getIdTransactionImportTemplate() {
    return idTransactionImportTemplate;
  }

  public void setIdTransactionImportTemplate(Integer idTransactionImportTemplate) {
    this.idTransactionImportTemplate = idTransactionImportTemplate;
  }

  public String getLastMatchingProperty() {
    return lastMatchingProperty;
  }

  public void setLastMatchingProperty(String lastMatchingProperty) {
    this.lastMatchingProperty = lastMatchingProperty;
  }

  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(String errorMessage) {
    this.errorMessage = errorMessage;
  }

  @Override
  public Integer getId() {
    return idTransactionPosFailed;
  }

  @Override
  public String toString() {
    return "ImportTransactionPosFailed [idTransactionPosFailed=" + idTransactionPosFailed
        + ", idTransactionImportTemplate=" + idTransactionImportTemplate + ", lastMatchingProperty="
        + lastMatchingProperty + ", idTransactionPos=" + idTransactionPos + "]";
  }

}
