export enum AlgoStrategyImplementationType {
  AS_HOLDING_TOP_REBALANCING = 1,
  AS_OBSERVED_SECURITY_ABSOLUTE_PRICE = 65,
  AS_HOLDING_TOP_GAIN_LOSE = 66,
  AS_OBSERVED_SECURITY_PERIOD_PRICE_GAIN_LOSE_PERCENT = 67,
  AS_OBSERVED_SECURITY_MEAN_REVERSION_DIP = 68,
  AS_OBSERVED_SECURITY_MA_CROSSING = 69,
  AS_OBSERVED_SECURITY_RSI_THRESHOLD = 70,
  AS_OBSERVED_SECURITY_EXPRESSION = 71
}
