export enum AlgoStrategyImplementationType {
  AS_REBALANCING = 1,
  AS_ABSOLUTE_PRICE_ALERT = 65,
  AS_HOLDING_GAIN_LOSE_PERCENTAGE_ALERT = 66,
  AS_PERIOD_PRICE_GAIN_LOSE_PERCENT_ALERT = 67,
  AS_MEAN_REVERSION_DIP = 68,
  AS_MA_CROSSING_ALERT = 69,
  AS_RSI_THRESHOLD_ALERT = 70,
  AS_EXPRESSION_ALERT = 71
}
