export enum EndpointOption {
  SKIP_WEEKEND_DATA = 'SKIP_WEEKEND_DATA',
  REMOVE_DUPLICATE_DATES = 'REMOVE_DUPLICATE_DATES',
  INTRADAY_USE_LAST_BAR = 'INTRADAY_USE_LAST_BAR'
}

export const ENDPOINT_OPTION_BY_FEED: Record<string, EndpointOption[]> = {
  FS_HISTORY: [EndpointOption.SKIP_WEEKEND_DATA, EndpointOption.REMOVE_DUPLICATE_DATES],
  FS_INTRA: [EndpointOption.INTRADAY_USE_LAST_BAR]
};
