import {GenericConnectorFieldMapping} from './generic.connector.field.mapping';

export class GenericConnectorEndpoint {
  idEndpoint: number = null;
  feedSupport: string = null;
  instrumentType: string = null;
  urlTemplate: string = null;
  httpMethod: string = null;
  responseFormat: string = null;
  numberFormat: string = null;
  dateFormatType: string = null;
  dateFormatPattern: string = null;
  jsonDataStructure: string = null;
  jsonDataPath: string = null;
  jsonColumnNamesPath: string = null;
  jsonStatusPath: string = null;
  jsonStatusOkValue: string = null;
  csvDelimiter: string = null;
  csvSkipHeaderLines: number = null;
  htmlCssSelector: string = null;
  htmlExtractMode: string = null;
  htmlTextCleanup: string = null;
  htmlExtractRegex: string = null;
  htmlSplitDelimiter: string = null;
  tickerBuildStrategy: string = null;
  currencyPairSeparator: string = null;
  currencyPairSuffix: string = null;
  tickerUppercase: boolean = false;
  maxDataPoints: number = null;
  paginationEnabled: boolean = false;
  everUsedSuccessfully: boolean = false;
  endpointOptions: string[] = [];
  fieldMappings: GenericConnectorFieldMapping[] = [];
}
