#!/usr/bin/env python3
"""
Intersect two security export CSV files and produce a CSV for GTNet Security Import upload.

Usage:
    python intersect_securities.py export_a.csv export_b.csv -o import_b.csv

Input format (semicolon-separated, no header, columns: isin;tickerSymbol;currency):
    Generated by:
        mariadb -u user -p grafioschtrader -e "
          SELECT IFNULL(s.isin, '') AS isin, IFNULL(s.ticker_symbol, '') AS tickerSymbol, s.currency
          FROM security s
          WHERE s.isin IS NOT NULL OR s.ticker_symbol IS NOT NULL
        " --batch --skip-column-names | tr '\t' ';' > export.csv

Output: semicolon-separated CSV with header "isin;tickerSymbol;currency" ready for upload
        via GTNetSecurityImportTableComponent.
"""
import argparse
import sys


def read_securities(filepath):
    """Read a semicolon-separated export file and return a list of (isin, ticker, currency) tuples."""
    rows = []
    with open(filepath, encoding='utf-8') as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            parts = line.split(';')
            if len(parts) < 3:
                print(f"WARNING: {filepath}:{lineno} skipped (expected 3 columns, got {len(parts)})", file=sys.stderr)
                continue
            isin = parts[0].strip().upper()
            ticker = parts[1].strip().upper()
            currency = parts[2].strip().upper()
            if not isin and not ticker:
                print(f"WARNING: {filepath}:{lineno} skipped (no ISIN and no ticker)", file=sys.stderr)
                continue
            if not currency or len(currency) != 3:
                print(f"WARNING: {filepath}:{lineno} skipped (invalid currency '{currency}')", file=sys.stderr)
                continue
            rows.append((isin, ticker, currency))
    return rows


def build_key_sets(rows):
    """Build lookup sets: one keyed by isin+currency, one by ticker+currency (for rows without ISIN)."""
    isin_keys = set()
    ticker_keys = set()
    for isin, ticker, currency in rows:
        if isin:
            isin_keys.add((isin, currency))
        elif ticker:
            ticker_keys.add((ticker, currency))
    return isin_keys, ticker_keys


def intersect(rows_a, rows_b):
    """Return rows from A that also exist in B, matched by isin+currency or ticker+currency."""
    isin_keys_b, ticker_keys_b = build_key_sets(rows_b)

    result = []
    seen = set()
    for isin, ticker, currency in rows_a:
        if isin:
            key = ('isin', isin, currency)
            match = (isin, currency) in isin_keys_b
        elif ticker:
            key = ('ticker', ticker, currency)
            match = (ticker, currency) in ticker_keys_b
        else:
            continue

        if match and key not in seen:
            seen.add(key)
            result.append((isin, ticker, currency))

    return result


def main():
    parser = argparse.ArgumentParser(description='Intersect two security CSV exports for GTNet import.')
    parser.add_argument('file_a', help='Export CSV from database A')
    parser.add_argument('file_b', help='Export CSV from database B')
    parser.add_argument('-o', '--output', default='import_b.csv', help='Output CSV file (default: import_b.csv)')
    args = parser.parse_args()

    rows_a = read_securities(args.file_a)
    rows_b = read_securities(args.file_b)
    print(f"Read {len(rows_a)} securities from {args.file_a}", file=sys.stderr)
    print(f"Read {len(rows_b)} securities from {args.file_b}", file=sys.stderr)

    common = intersect(rows_a, rows_b)
    print(f"Found {len(common)} securities in common", file=sys.stderr)

    with open(args.output, 'w', encoding='utf-8', newline='') as f:
        f.write('isin;tickerSymbol;currency\n')
        for isin, ticker, currency in common:
            f.write(f'{isin};{ticker};{currency}\n')

    print(f"Wrote {args.output} ({len(common)} rows)", file=sys.stderr)


if __name__ == '__main__':
    main()
