import {test, expect, Locator, Page} from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import {loginAsCsvUser, parseCsvRow} from './helpers';

/**
 * One risk-free-rate mapping to create, as described by a row of the generated CSV.
 */
interface MappingRow {
  /** ISO 4217 currency code (dropdown value in column 1). */
  currency: string;
  /** Security name — the visible label of the instrument dropdown (column 2) and the verify text. */
  securityName: string;
  /** FRED series id (url_history_extend), shown read-only in column 3. */
  fredSeriesId: string;
  /** When true the spec deletes this mapping after creating it and then recreates it. */
  recreate: boolean;
}

// Generated by nv.bat from the master DB's FRED risk-free-rate securities (see backend/nv.bat block A2).
const CSV_PATH = path.resolve(__dirname,
  '../../backend/grafioschtrader-server/src/test/resources/testdata/generated/riskfreeratemapping.csv');

// The spec logs in as 'admin' (hg@hugograf.com, locale de-CH), so the tree node and the confirm dialog render in
// German; the English alternatives keep the spec working for an English test user as well.
const BASE_DATA_MATCH = /Base data|Basisdaten/i;
const VIEW_MATCH = /Risk-free rate mapping|Risikofreier/i;
const CONFIRM_MATCH = /Confirmation|Bestätigung/i;
const YES_MATCH = /yes|ja/i;

// Locators scoped to this component's editable table.
const TRASH_BTN = 'editable-table button:has(i.pi-trash)';
const PLUS_BTN = 'editable-table button:has(i.pi-plus)';

function loadMappings(): MappingRow[] {
  // The CSV is regenerated by nv.bat and committed alongside the other generated testdata. When it is not present
  // (a fresh checkout before nv.bat has run), degrade to zero tests instead of breaking the Playwright collection.
  if (!fs.existsSync(CSV_PATH)) {
    console.warn(`CSV ${CSV_PATH} not found - skipping risk-free-rate-mapping e2e (run nv.bat to generate it).`);
    return [];
  }
  return fs.readFileSync(CSV_PATH, 'utf-8')
    .split(/\r?\n/)
    .filter(line => line.trim().length > 0)
    .map(line => {
      const cols = parseCsvRow(line);
      return {currency: cols[0], securityName: cols[1], fredSeriesId: cols[2], recreate: cols[3] === 'true'};
    });
}

/**
 * Opens Base Data -> Risk-free rate mapping and returns the editable-table locator. The mapping view is a leaf of the
 * Base Data navigation tree (route /riskfreeratemapping).
 */
async function openMappingView(page: Page): Promise<Locator> {
  const baseDataNode = page.locator('.p-tree-node-content', {hasText: BASE_DATA_MATCH}).first();
  await baseDataNode.waitFor({state: 'visible', timeout: 15_000});
  await baseDataNode.dblclick();

  const viewNode = page.locator('.p-tree-node-content', {hasText: VIEW_MATCH}).first();
  await viewNode.waitFor({state: 'visible', timeout: 15_000});
  await viewNode.click();
  await page.waitForURL(/\/riskfreeratemapping/, {timeout: 10_000});

  const table = page.locator('editable-table').first();
  await table.waitFor({state: 'visible', timeout: 10_000});
  return table;
}

/**
 * Accepts the PrimeNG confirmation dialog raised by a delete.
 */
async function acceptConfirm(page: Page): Promise<void> {
  const dialog = page.getByRole('alertdialog', {name: CONFIRM_MATCH});
  await dialog.waitFor({state: 'visible', timeout: 5_000});
  await dialog.getByRole('button', {name: YES_MATCH}).click();
}

/**
 * Deletes every existing mapping row so the spec is repeatable against the live grafioschtrader_t without a DB reset.
 * Each delete triggers a confirm dialog and a server round-trip (readData reload), so wait for the trash-button count
 * to drop by one before the next iteration.
 */
async function deleteAllMappings(page: Page): Promise<void> {
  for (let guard = 0; guard < 30; guard++) {
    const count = await page.locator(TRASH_BTN).count();
    if (count === 0) {
      return;
    }
    await page.locator(TRASH_BTN).first().click();
    await acceptConfirm(page);
    await expect(page.locator(TRASH_BTN)).toHaveCount(count - 1, {timeout: 10_000});
  }
  throw new Error('deleteAllMappings did not converge - more than 30 leftover rows?');
}

/**
 * Creates one mapping via the inline editable table: click the caption "+" (adds an auto-editing row), pick the
 * currency (native select, column 1) and then the instrument (native select, column 2, options resolve once the
 * currency is set), save the row, and assert it appears in display mode.
 */
async function createMapping(page: Page, row: MappingRow): Promise<void> {
  await page.locator(PLUS_BTN).click();

  const editRow = page.locator('editable-table tr:has(select)');
  await editRow.waitFor({state: 'visible', timeout: 10_000});

  // Column 1: currency (option value = ISO code).
  await editRow.locator('select').first().selectOption(row.currency);
  // Column 2: instrument (option label = security name; single option for the chosen currency).
  await editRow.locator('select').nth(1).selectOption({label: row.securityName});

  // Save (pi-check) and wait for the row to leave edit mode (server reload removes the inline selects).
  await editRow.locator('button:has(i.pi-check)').click();
  await expect(page.locator('editable-table tr:has(select)')).toHaveCount(0, {timeout: 10_000});

  await expect(page.locator('editable-table td', {hasText: row.securityName}).first())
    .toBeVisible({timeout: 5_000});
}

/**
 * Deletes the mapping row identified by its security name and asserts it disappears.
 */
async function deleteMapping(page: Page, securityName: string): Promise<void> {
  const row = page.locator('editable-table tr', {hasText: securityName}).first();
  await row.waitFor({state: 'visible', timeout: 10_000});
  await row.locator('button:has(i.pi-trash)').click();
  await acceptConfirm(page);
  await expect(page.locator('editable-table td', {hasText: securityName})).toHaveCount(0, {timeout: 10_000});
}

test.describe.serial('Risk-free rate mapping: create all, delete one, recreate (CSV-driven)', () => {
  const mappings = loadMappings();

  test('creates every mapping, then deletes and recreates the flagged one(s)', async ({page}) => {
    test.skip(mappings.length === 0, 'riskfreeratemapping.csv not generated - run nv.bat.');

    await loginAsCsvUser(page, 'admin'); // hg@hugograf.com, ROLE_ADMIN (not daily-limited)
    await openMappingView(page);

    // Repeatable: clear any leftovers from a previous failed run before creating.
    await deleteAllMappings(page);

    // Create all mappings from the CSV.
    for (const row of mappings) {
      await createMapping(page, row);
    }
    await expect(page.locator(TRASH_BTN)).toHaveCount(mappings.length, {timeout: 10_000});

    // Delete and recreate the flagged mapping(s) (recreate=true, i.e. USD).
    for (const row of mappings.filter(m => m.recreate)) {
      await deleteMapping(page, row.securityName);
      await createMapping(page, row);
    }

    // Final state: all mappings present again.
    await expect(page.locator(TRASH_BTN)).toHaveCount(mappings.length, {timeout: 10_000});
    for (const row of mappings) {
      await expect(page.locator('editable-table td', {hasText: row.securityName}).first()).toBeVisible();
    }
  });
});
