import { test, expect, Locator, Page } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { loginAsFixtureUser } from './helpers';

interface RuleSetRow {
  mic: string;
  name: string;
  ruleYaml: string;
  extendsName: string;
  e2e: string;
}

// The fixture is JSON (not CSV): rule_yaml is multi-line YAML that the pipe-delimited testdata CSVs cannot carry.
const FIXTURE_PATH = path.resolve(
  __dirname,
  '../../backend/grafioschtrader-server/src/test/resources/testdata/generated/trading_calendar_rule_set.json'
);

// The e2e creates its rule set as an alias (empty YAML + a parent), so the Monaco YAML editor is never touched.
// Any stable seeded 'd' rule set works as the parent; SIX Swiss Exchange (XSWX) is always seeded.
const PARENT_MATCH = /SIX Swiss Exchange/i;

// The spec logs in as 'user' (locale de-CH), so every text selector matches the German and the
// English label — same convention as manage-client.helpers.ts.
const RX = {
  baseDataNode: /(Base Data|Basisdaten)/i,
  stockexchangeNode: /^\s*(Stock\s*exchange|Handelsplatz)\s*$/i,
  ruleTab: /(Trading calendar rules|Handelskalender-Regeln)/i,
  createItem: /(Create.*Trading.*calendar.*rules|Erstellen.*Handelskalender-Regeln)/i,
  deleteItem: /(Delete|L.schen)/i,
  confirmHeader: /(Confirmation|Best.tigung)/i,
  confirmYes: /^\s*(yes|ja)\s*$/i
};

function loadE2ERows(): RuleSetRow[] {
  // The fixture is regenerated by nv.bat and committed alongside the other generated testdata. When it is not present
  // (a fresh checkout before nv.bat has run), degrade to zero tests instead of breaking the whole Playwright collection.
  if (!fs.existsSync(FIXTURE_PATH)) {
    console.warn(
      `Fixture ${FIXTURE_PATH} not found - skipping trading calendar rule set e2e (run nv.bat to generate it).`
    );
    return [];
  }
  const rows: RuleSetRow[] = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf-8'));
  return rows.filter((r) => r.e2e === 'e');
}

/**
 * Opens the "Trading calendar rules" view and returns the table locator. The rule sets are not a tree node of their
 * own: they live on the second tab of the "Stock exchange" base data view (Base Data -> Stock exchange -> rule sets
 * tab, route .../stockexchange/rulesets).
 */
async function openRuleSetView(page: Page): Promise<Locator> {
  const baseDataNode = page.locator('.p-tree-node-content', { hasText: RX.baseDataNode }).first();
  await baseDataNode.waitFor({ state: 'visible', timeout: 15_000 });
  await baseDataNode.dblclick();

  const stockexchangeNode = page.locator('.p-tree-node-content', { hasText: RX.stockexchangeNode }).first();
  await stockexchangeNode.waitFor({ state: 'visible', timeout: 15_000 });
  await stockexchangeNode.click();

  const ruleTab = page.locator('p-tab').filter({ hasText: RX.ruleTab }).first();
  await ruleTab.waitFor({ state: 'visible', timeout: 15_000 });
  await ruleTab.click();
  await page.waitForURL(/\/rulesets/, { timeout: 10_000 });

  const table = page.locator('p-table, .p-datatable').first();
  await table.waitFor({ state: 'visible', timeout: 10_000 });
  return table;
}

/**
 * Deletes the rule set row with the given name if it is present (leftover from a previous failed run), so the spec is
 * repeatable against the live grafioschtrader_t without a DB reset.
 */
async function deleteRuleSetIfPresent(page: Page, table: Locator, name: string): Promise<void> {
  // The rows arrive asynchronously after the view is shown. Without waiting for them, count() reports 0 for a table
  // that is merely still empty, the cleanup is skipped, and the following create fails on the duplicate MIC. The
  // seeded 'd' rule sets guarantee that at least one row shows up.
  await table.locator('tr[data-p-selectable-row]').first().waitFor({ state: 'visible', timeout: 15_000 });

  const row = page.locator('tr[data-p-selectable-row]', { hasText: name }).first();
  if ((await row.count()) === 0) {
    return;
  }
  await row.click();
  await page.waitForTimeout(300);
  await row.click({ button: 'right' });

  const menuList = page.locator('[role="menu"]:visible');
  await menuList.waitFor({ state: 'visible', timeout: 5_000 });
  await menuList.getByText(RX.deleteItem).first().click();

  const confirmDialog = page.getByRole('alertdialog', { name: RX.confirmHeader });
  await confirmDialog.waitFor({ state: 'visible', timeout: 5_000 });
  await confirmDialog.getByRole('button', { name: RX.confirmYes }).click();

  await expect(page.locator('td', { hasText: name })).toHaveCount(0, { timeout: 10_000 });
}

/**
 * Creates a rule set as an alias: sets name and MIC, picks a seeded parent in the idExtendsRuleSet dropdown and leaves
 * the YAML editor empty. The backend allows an empty YAML when a parent is set.
 */
async function createRuleSet(page: Page, table: Locator, row: RuleSetRow): Promise<void> {
  await table.click();
  await page.waitForTimeout(300);
  await table.click({ button: 'right' });

  const menuList = page.locator('[role="menu"]:visible');
  await menuList.waitFor({ state: 'visible', timeout: 5_000 });
  await menuList.getByText(RX.createItem).first().click();

  const dialog = page.locator('.p-dialog');
  await dialog.waitFor({ state: 'visible', timeout: 10_000 });

  const nameInput = dialog.locator('input#name');
  await nameInput.click();
  await nameInput.fill(row.name);
  await nameInput.dispatchEvent('input');
  await nameInput.blur();

  const micInput = dialog.locator('input#mic');
  await micInput.click();
  await micInput.fill(row.mic);
  await micInput.dispatchEvent('input');
  await micInput.blur();

  // Pick a seeded parent so the YAML may stay empty. Resolve the option value by its visible text (ids differ per DB).
  const parentSelect = dialog.locator('select#idExtendsRuleSet');
  const parentOption = parentSelect.locator('option', { hasText: PARENT_MATCH }).first();
  await parentOption.waitFor({ state: 'attached', timeout: 10_000 });
  const parentValue = await parentOption.getAttribute('value');
  await parentSelect.selectOption(parentValue);
  await parentSelect.dispatchEvent('change');

  await dialog.locator('button[type="submit"]').click();
  await dialog.waitFor({ state: 'hidden', timeout: 10_000 });

  await expect(page.locator('td', { hasText: row.name }).first()).toBeVisible({ timeout: 5_000 });
}

/**
 * Deletes the rule set row with the given name and asserts it disappears.
 */
async function deleteRuleSet(page: Page, name: string): Promise<void> {
  const row = page.locator('tr[data-p-selectable-row]', { hasText: name }).first();
  await row.waitFor({ state: 'visible', timeout: 10_000 });
  await row.click();
  await page.waitForTimeout(300);
  await row.click({ button: 'right' });

  const menuList = page.locator('[role="menu"]:visible');
  await menuList.waitFor({ state: 'visible', timeout: 5_000 });
  await menuList.getByText(RX.deleteItem).first().click();

  const confirmDialog = page.getByRole('alertdialog', { name: RX.confirmHeader });
  await confirmDialog.waitFor({ state: 'visible', timeout: 5_000 });
  await confirmDialog.getByRole('button', { name: RX.confirmYes }).click();

  await expect(page.locator('td', { hasText: name })).toHaveCount(0, { timeout: 10_000 });
}

test.describe
  .serial("Trading calendar rule set: create, delete and recreate (e2e='e' rows from shared fixture)", () => {
  const rows = loadE2ERows();

  for (const row of rows) {
    test(`creates, deletes and recreates rule set: ${row.name} (${row.mic})`, async ({ page }) => {
      await loginAsFixtureUser(page, 'user');
      const table = await openRuleSetView(page);

      // Repeatable: remove a leftover row from a previous failed run before creating.
      await deleteRuleSetIfPresent(page, table, row.name);

      await createRuleSet(page, table, row);
      await deleteRuleSet(page, row.name);
      await createRuleSet(page, table, row);
    });
  }
});
