"""Reproducibly assemble the standalone installer without executing source code."""

import argparse
import os
from pathlib import Path
import re
import sys
import tempfile


MODULES = (
    "00-common.sh", "10-inventory.sh", "20-compat.sh", "30-questions.sh", "35-dialogs.sh",
    "40-plan.sh", "50-state.sh", "60-core.sh", "70-app.sh",
    "80-web-nginx.sh", "81-web-sites.sh", "90-mail.sh", "95-result.sh", "96-bootstrap.sh", "99-main.sh",
)
HEADER = "# Generated by util/installer/build.sh; edit src/ and rebuild.\n"
HEREDOC = re.compile(r"^# @python ([a-z][a-z0-9-]*\.py)\n", re.MULTILINE)
INLINE = re.compile(r"@python-inline ([a-z][a-z0-9-]*\.py)@")


def read_source(path):
    """Require portable text so checkout settings cannot change the bundle."""
    data = path.read_bytes()
    if b"\r" in data or data.startswith(b"\xef\xbb\xbf") or not data.endswith(b"\n"):
        raise ValueError(f"{path.name}: UTF-8 without BOM, LF and a final newline required")
    return data.decode("utf-8")


def assemble(directory):
    """Expand only declared markers, preserving shell statement and argument order."""
    source = directory / "src"
    actual = {path.name for path in source.glob("*.sh")}
    if actual != set(MODULES):
        raise ValueError(f"Shell module inventory differs: {sorted(actual ^ set(MODULES))}")
    used = set()

    def helper(name):
        used.add(name)
        code = read_source(source / "py" / name)
        compile(code, name, "exec")
        return code

    def heredoc(match):
        code = helper(match[1])
        if "PY" in code.splitlines():
            raise ValueError(f"{match[1]}: reserved heredoc delimiter PY")
        return code

    def inline(match):
        # The placeholder sits inside shell single quotes. Escape new Python
        # apostrophes at the shell boundary; stdin remains available for JSON.
        return helper(match[1]).removesuffix("\n").replace("'", "'\"'\"'")

    modules = []
    for name in MODULES:
        module = read_source(source / name)
        module = HEREDOC.sub(heredoc, module)
        module = INLINE.sub(inline, module)
        if "@python" in module:
            raise ValueError(f"{name}: unresolved Python marker")
        modules.append(module)
    actual = {path.name for path in (source / "py").glob("*.py")}
    if used != actual:
        raise ValueError(f"Unused Python helpers: {sorted(actual - used)}")
    script = "".join(modules)
    if not script.startswith("#!/bin/bash\n"):
        raise ValueError("The first module must provide the Bash shebang")
    return script.replace("#!/bin/bash\n", "#!/bin/bash\n" + HEADER, 1).encode("utf-8")


def build(directory, check=False):
    """Compare without writes, or atomically publish a completely validated bundle."""
    data = assemble(directory)
    target = directory / "gt-install.sh"
    current = target.read_bytes() if target.exists() else None
    if current == data:
        return 0
    if check:
        print("gt-install.sh differs from src/; run bash util/installer/build.sh", file=sys.stderr)
        return 1
    mode = target.stat().st_mode & 0o777 if target.exists() else 0o644
    descriptor, name = tempfile.mkstemp(prefix=".gt-install-", suffix=".tmp", dir=directory)
    temporary = Path(name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        os.replace(temporary, target)
    finally:
        temporary.unlink(missing_ok=True)
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on bundle drift without writing files")
    args = parser.parse_args()
    try:
        return build(Path(__file__).resolve().parent, args.check)
    except (OSError, ValueError, SyntaxError) as error:
        print(f"Installer build failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
