export enum GlobalSessionNames {
  UPDATE_TIME = 'updateTimeout',
  START_FEED_DATE = 'startFeedDate',
  MAX_WATCHLIST_LENGTH = 'maxWatchlistLength',
  ID_TENANT = 'idTenant',
  ID_USER = 'idUser',
  LOCALE = 'locale',
  DECIMAL_SEPARATOR = 'decimalSeparator',
  THOUSANDS_SEPARATOR = 'thousandsSeparator',
  LANGUAGE = 'language',
  JWT = 'jwt',
  ROLES = 'roles',
  REPORT_UNTIL_DATE = 'untilDate',
  ENTITY_KEY_MAPPING = 'entityKeyMapping',
  USE_WEBSOCKET = 'useWebsocket',
  USE_ALGO = 'useAlgo',
  CRYPTOS = 'crypotcurrencies',
  TAB_MENU_TENANT = 'tabMenuTenant',
  TAB_MENU_PORTFOLIO = 'tabMenuPortfolio',
  PERFORMANCE_DATE_FROM = 'performanceDateFrom',
  STANDARD_PRECISION = 'standardPrecision',
  CURRENCY_PRECISION = 'currencyPrecision',
  UI_SHOW_MY_PROPERTY = 'uiShowMyProperty',
  USER_FORM_DEFINITION = 'userFormDefinition'
}
