package grafioschtrader.gtnet.model.msg;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Payload for the initial handshake message (GT_NET_FIRST_HANDSHAKE_S).
 *
 * During the handshake, the initiating domain generates a GUID token and sends it to the remote domain.
 * The remote stores this token as its {@code tokenRemote} for the initiator's GTNet entry, and will
 * include it in the Authorization header when making requests back to the initiator.
 *
 * The MessageEnvelope also includes the full GTNet entity of the sender in its payload field,
 * providing the remote with timezone, capability flags, and other configuration.
 *
 * @see grafioschtrader.entities.GTNet#tokenThis for local token generation
 * @see grafioschtrader.entities.GTNet#tokenRemote for received token storage
 */
@Schema(description = """
    Payload for the initial handshake message between GTNet peers. Contains the locally generated authentication
    token that the remote must use in future requests. The full GTNet entity is transmitted separately in the
    MessageEnvelope payload field.""")
public class FirstHandshakeMsg {

  @Schema(description = """
      The authentication token generated by the sender. The receiver stores this as their tokenRemote for this
      peer and must include it in the Authorization header of all subsequent M2M requests.""")
  public String tokenThis;

  public FirstHandshakeMsg() {
  }

  public FirstHandshakeMsg(String tokenThis) {
    this.tokenThis = tokenThis;
  }

}
