name: manual GT
on:
  push:
    branches:
      - master
    paths:
      - manual/**
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        working-directory: ./manual
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        working-directory: ./manual
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        working-directory: ./manual
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./manual/public