name: Deploy Javadoc

on:
  push:
    branches:
      - main
      - master
    # löst nur aus, wenn sich in einem Modul etwas ändert
    paths:
      - 'backend/**'
      - 'grafiosch-base/**'
      - 'grafiosch-server-base/**'
      - 'grafioschtrader-common/**'
      - 'Grafioschtrader/**'
  workflow_dispatch: {}

jobs:
  publish:
    name: Generate & Deploy Javadoc
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '21'
          cache: maven

      - name: Generate Javadoc for all modules
        working-directory: backend
        run: |
          mvn -B javadoc:aggregate \
            -Daggregate=true \
            -DreportOutputDirectory=javadoc \
            -Dmaven.javadoc.failOnError=false \
            -Ddoclint=all,-missing
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: backend/target/reports/apidocs
          token: ${{ secrets.GITHUB_TOKEN }}


