name: Deploy Javadoc

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'backend/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: maven

      - name: Generate Javadoc
        run: mvn javadoc:aggregate -B -Daggregate=true -DreportOutputDirectory=./javadoc

      - name: Deploy Javadoc to GitHub Pages
        uses: MathieuSoysal/Javadoc-publisher.yml@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: gh-pages
          java-version: '21'
          source-folder: javadoc
          project: maven