name: Generate and Publish Backend Documentation

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - master # Trigger only on master branch upon push
  workflow_dispatch: # Allows manual triggering

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # Build the project with Maven, skipping tests
      - name: Build with Maven
        working-directory: backend
        run: mvn clean package -pl grafioschtrader-server -am -DskipTests

      # Create directory for documentation
      - name: Prepare Documentation Directory
        run: |
          mkdir -p docs/javadoc
          # Copy Javadoc HTML if available
          if [ -d "backend/grafioschtrader-server/target/site/apidocs" ]; then
            cp -r backend/grafioschtrader-server/target/site/apidocs/* docs/javadoc/
          else
            # Fallback: Extract Javadoc from *-javadoc.jar
            unzip -o backend/grafioschtrader-server/target/*-javadoc.jar -d docs/javadoc/
          fi
          # Copy OpenAPI JSON
          cp backend/grafioschtrader-server/target/generated-docs/openapi.json docs/
          # Create Swagger UI HTML
          cat <<EOF > docs/index.html
          <!DOCTYPE html>
          <html>
          <head>
              <title>Grafioschtrader Swagger UI</title>
              <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css" />
          </head>
          <body>
              <div id="swagger-ui"></div>
              <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
              <script>
                  window.onload = function() {
                      SwaggerUIBundle({
                          url: "./openapi.json",
                          dom_id: '#swagger-ui',
                          presets: [
                              SwaggerUIBundle.presets.apis,
                              SwaggerUIBundle.SwaggerUIStandalonePreset
                          ]
                      })
                  }
              </script>
          </body>
          </html>
          EOF

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs