name: Generate and Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      # 3. Build Spring Boot server, generate Javadoc and OpenAPI spec
      - name: Build server and generate docs
        run: |
          cd backend/grafioschtrader-server
          mvn clean javadoc:javadoc springdoc-openapi:generate

      # 4. Prepare docs directory for GitHub Pages
      - name: Prepare docs directory
        run: |
          rm -rf docs
          mkdir -p docs/swagger

          # Copy generated Javadoc
          cp -R backend/grafioschtrader-server/target/site/apidocs/* docs/

          # Copy generated OpenAPI spec
          cp backend/grafioschtrader-server/target/generated-docs/openapi.json docs/swagger/

          # Download and extract Swagger UI distribution
          wget -qO- https://github.com/swagger-api/swagger-ui/archive/refs/tags/v4.15.5.tar.gz \
            | tar xz --strip-components=1 swagger-ui-4.15.5/dist
          cp -R * docs/swagger/

          # Create an index.html that loads the OpenAPI spec
          cat > docs/swagger/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <title>API Documentation</title>
              <link rel="stylesheet" href="swagger-ui.css" />
              <link rel="icon" href="favicon-32x32.png" sizes="32x32" />
              <link rel="icon" href="favicon-16x16.png" sizes="16x16" />
              <style> body { margin:0; background:#fafafa; } </style>
            </head>
            <body>
              <div id="swagger-ui"></div>
              <script src="swagger-ui-bundle.js"></script>
              <script src="swagger-ui-standalone-preset.js"></script>
              <script>
                window.onload = function() {
                  SwaggerUIBundle({
                    url: './openapi.json',
                    dom_id: '#swagger-ui',
                    deepLinking: true,
                    presets: [
                      SwaggerUIBundle.presets.apis,
                      SwaggerUIStandalonePreset
                    ],
                    layout: 'StandaloneLayout'
                  });
                };
              </script>
            </body>
          </html>
          EOF

      # 5. Upload the docs directory as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy-pages:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
